//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1008
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test._360doo.com.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.PAHaoCheTokenServiceSoap")]
    public interface PAHaoCheTokenServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 RequestAccessTokenResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RequestAccessToken", ReplyAction="*")]
        Test._360doo.com.ServiceReference1.RequestAccessTokenResponse RequestAccessToken(Test._360doo.com.ServiceReference1.RequestAccessTokenRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RequestAccessTokenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RequestAccessToken", Namespace="http://tempuri.org/", Order=0)]
        public Test._360doo.com.ServiceReference1.RequestAccessTokenRequestBody Body;
        
        public RequestAccessTokenRequest() {
        }
        
        public RequestAccessTokenRequest(Test._360doo.com.ServiceReference1.RequestAccessTokenRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class RequestAccessTokenRequestBody {
        
        public RequestAccessTokenRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RequestAccessTokenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RequestAccessTokenResponse", Namespace="http://tempuri.org/", Order=0)]
        public Test._360doo.com.ServiceReference1.RequestAccessTokenResponseBody Body;
        
        public RequestAccessTokenResponse() {
        }
        
        public RequestAccessTokenResponse(Test._360doo.com.ServiceReference1.RequestAccessTokenResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RequestAccessTokenResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RequestAccessTokenResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string message;
        
        public RequestAccessTokenResponseBody() {
        }
        
        public RequestAccessTokenResponseBody(string RequestAccessTokenResult, string message) {
            this.RequestAccessTokenResult = RequestAccessTokenResult;
            this.message = message;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PAHaoCheTokenServiceSoapChannel : Test._360doo.com.ServiceReference1.PAHaoCheTokenServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PAHaoCheTokenServiceSoapClient : System.ServiceModel.ClientBase<Test._360doo.com.ServiceReference1.PAHaoCheTokenServiceSoap>, Test._360doo.com.ServiceReference1.PAHaoCheTokenServiceSoap {
        
        public PAHaoCheTokenServiceSoapClient() {
        }
        
        public PAHaoCheTokenServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PAHaoCheTokenServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PAHaoCheTokenServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PAHaoCheTokenServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Test._360doo.com.ServiceReference1.RequestAccessTokenResponse Test._360doo.com.ServiceReference1.PAHaoCheTokenServiceSoap.RequestAccessToken(Test._360doo.com.ServiceReference1.RequestAccessTokenRequest request) {
            return base.Channel.RequestAccessToken(request);
        }
        
        public string RequestAccessToken(out string message) {
            Test._360doo.com.ServiceReference1.RequestAccessTokenRequest inValue = new Test._360doo.com.ServiceReference1.RequestAccessTokenRequest();
            inValue.Body = new Test._360doo.com.ServiceReference1.RequestAccessTokenRequestBody();
            Test._360doo.com.ServiceReference1.RequestAccessTokenResponse retVal = ((Test._360doo.com.ServiceReference1.PAHaoCheTokenServiceSoap)(this)).RequestAccessToken(inValue);
            message = retVal.Body.message;
            return retVal.Body.RequestAccessTokenResult;
        }
    }
}
